version: '3.8'

services:
  ros-humble:
    build:
      context: .
      dockerfile: Dockerfile
    image: therasonic
    ports:
      - "5900:5900"
      - "6080:6080"
      - "50002:50002"
    network_mode: "host"
    environment:
        - X11_ENABLED=1
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1
        - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - ./:/home/robot/ws
    stdin_open: true
    tty: true
